<mxfile host="app.diagrams.net" agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36 Edg/142.0.0.0" version="29.2.3" pages="4">
  <diagram name="Diagrama de contexto" id="tcikgAr0Kv5F-jqcZc8q">
    <mxGraphModel dx="1907" dy="555" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="827" pageHeight="1169" math="0" shadow="0">
      <root>
        <mxCell id="0" />
        <mxCell id="1" parent="0" />
        <object placeholders="1" c4Name="Personal" c4Type="User" c4Description="Usuario que usara el modulo" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;%c4Name%&lt;/b&gt;&lt;/font&gt;&lt;div&gt;[%c4Type%]&lt;/div&gt;&lt;br&gt;&lt;div&gt;&lt;font style=&quot;font-size: 11px&quot;&gt;&lt;font color=&quot;#cccccc&quot;&gt;%c4Description%&lt;/font&gt;&lt;/div&gt;" id="FdgXNTerTwK2w4FDOcPx-7">
          <mxCell parent="1" style="html=1;fontSize=11;dashed=0;whiteSpace=wrap;fillColor=#083F75;strokeColor=#06315C;fontColor=#ffffff;shape=mxgraph.c4.person2;align=center;metaEdit=1;points=[[0.5,0,0],[1,0.5,0],[1,0.75,0],[0.75,1,0],[0.5,1,0],[0.25,1,0],[0,0.75,0],[0,0.5,0]];resizable=0;" vertex="1">
            <mxGeometry height="180" width="200" x="-46" y="492" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Name="BancoLitoral (SWI)" c4Type="Software System" c4Description="Sistema Web Interno" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;%c4Name%&lt;/b&gt;&lt;/font&gt;&lt;div&gt;[%c4Type%]&lt;/div&gt;&lt;br&gt;&lt;div&gt;&lt;font style=&quot;font-size: 11px&quot;&gt;&lt;font color=&quot;#cccccc&quot;&gt;%c4Description%&lt;/font&gt;&lt;/div&gt;" id="FdgXNTerTwK2w4FDOcPx-8">
          <mxCell parent="1" style="rounded=1;whiteSpace=wrap;html=1;labelBackgroundColor=none;fillColor=#1061B0;fontColor=#ffffff;align=center;arcSize=10;strokeColor=#0D5091;metaEdit=1;resizable=0;points=[[0.25,0,0],[0.5,0,0],[0.75,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.75,1,0],[0.5,1,0],[0.25,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];" vertex="1">
            <mxGeometry height="120" width="240" x="320" y="520" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Name="Exchange365" c4Type="Software System" c4Description="Servicio de Notificaciones de MS365" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;%c4Name%&lt;/b&gt;&lt;/font&gt;&lt;div&gt;[%c4Type%]&lt;/div&gt;&lt;br&gt;&lt;div&gt;&lt;font style=&quot;font-size: 11px&quot;&gt;&lt;font color=&quot;#cccccc&quot;&gt;%c4Description%&lt;/font&gt;&lt;/div&gt;" id="FdgXNTerTwK2w4FDOcPx-9">
          <mxCell parent="1" style="rounded=1;whiteSpace=wrap;html=1;labelBackgroundColor=none;fillColor=#8C8496;fontColor=#ffffff;align=center;arcSize=10;strokeColor=#736782;metaEdit=1;resizable=0;points=[[0.25,0,0],[0.5,0,0],[0.75,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.75,1,0],[0.5,1,0],[0.25,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];" vertex="1">
            <mxGeometry height="120" width="240" x="720" y="520" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Name="Oracle Database 12" c4Type="Esquema" c4Technology="PRODUCTO_SERVICIO" c4Description="Almacenar información del sistema" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;%c4Name%&lt;/b&gt;&lt;/font&gt;&lt;div&gt;[%c4Type%:&amp;nbsp;%c4Technology%]&lt;/div&gt;&lt;br&gt;&lt;div&gt;&lt;font style=&quot;font-size: 11px&quot;&gt;&lt;font color=&quot;#E6E6E6&quot;&gt;%c4Description%&lt;/font&gt;&lt;/div&gt;" id="FdgXNTerTwK2w4FDOcPx-11">
          <mxCell parent="1" style="shape=cylinder3;size=15;whiteSpace=wrap;html=1;boundedLbl=1;rounded=0;labelBackgroundColor=none;fillColor=#23A2D9;fontSize=12;fontColor=#ffffff;align=center;strokeColor=#0E7DAD;metaEdit=1;points=[[0.5,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.5,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];resizable=0;" vertex="1">
            <mxGeometry height="120" width="240" x="320" y="720" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Type="Relationship" id="FdgXNTerTwK2w4FDOcPx-20">
          <mxCell edge="1" parent="1" style="endArrow=blockThin;html=1;fontSize=10;fontColor=#404040;strokeWidth=1;endFill=1;strokeColor=#828282;elbow=vertical;metaEdit=1;endSize=14;startSize=14;jumpStyle=arc;jumpSize=16;rounded=0;edgeStyle=orthogonalEdgeStyle;entryX=0;entryY=0.5;entryDx=0;entryDy=0;entryPerimeter=0;" target="FdgXNTerTwK2w4FDOcPx-9">
            <mxGeometry relative="1" width="240" as="geometry">
              <mxPoint x="560" y="579.38" as="sourcePoint" />
              <mxPoint x="800" y="579.38" as="targetPoint" />
            </mxGeometry>
          </mxCell>
        </object>
        <object placeholders="1" c4Type="Relationship" id="FdgXNTerTwK2w4FDOcPx-21">
          <mxCell edge="1" parent="1" source="FdgXNTerTwK2w4FDOcPx-8" style="endArrow=blockThin;html=1;fontSize=10;fontColor=#404040;strokeWidth=1;endFill=1;strokeColor=#828282;elbow=vertical;metaEdit=1;endSize=14;startSize=14;jumpStyle=arc;jumpSize=16;rounded=0;edgeStyle=orthogonalEdgeStyle;exitX=0.5;exitY=1;exitDx=0;exitDy=0;exitPerimeter=0;" target="FdgXNTerTwK2w4FDOcPx-11">
            <mxGeometry relative="1" width="240" as="geometry">
              <mxPoint x="260" y="680" as="sourcePoint" />
              <mxPoint x="500" y="680" as="targetPoint" />
            </mxGeometry>
          </mxCell>
        </object>
        <object placeholders="1" c4Type="Relationship" id="FdgXNTerTwK2w4FDOcPx-24">
          <mxCell edge="1" parent="1" source="FdgXNTerTwK2w4FDOcPx-7" style="endArrow=blockThin;html=1;fontSize=10;fontColor=#404040;strokeWidth=1;endFill=1;strokeColor=#828282;elbow=vertical;metaEdit=1;endSize=14;startSize=14;jumpStyle=arc;jumpSize=16;rounded=0;edgeStyle=orthogonalEdgeStyle;exitX=1;exitY=0.5;exitDx=0;exitDy=0;exitPerimeter=0;">
            <mxGeometry relative="1" width="240" as="geometry">
              <mxPoint x="80" y="583" as="sourcePoint" />
              <mxPoint x="320" y="583" as="targetPoint" />
            </mxGeometry>
          </mxCell>
        </object>
      </root>
    </mxGraphModel>
  </diagram>
  <diagram name="Diagrama de contenedores" id="BWpKMdm4ExlGpE10qyzn">
    <mxGraphModel dx="1329" dy="683" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="827" pageHeight="1169" math="0" shadow="0">
      <root>
        <mxCell id="1n15_pKxOORiXK8SXrbd-0" />
        <mxCell id="1n15_pKxOORiXK8SXrbd-1" parent="1n15_pKxOORiXK8SXrbd-0" />
        <mxCell id="I9fNkN6Fc--YZo9XAbdK-5" edge="1" parent="1n15_pKxOORiXK8SXrbd-1" source="WMC1f1DDedSoK6EWAYH4-0" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;" target="WMC1f1DDedSoK6EWAYH4-3">
          <mxGeometry relative="1" as="geometry" />
        </mxCell>
        <object placeholders="1" c4Name="Personal" c4Type="User" c4Description="Usuario que usara el modulo" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;%c4Name%&lt;/b&gt;&lt;/font&gt;&lt;div&gt;[%c4Type%]&lt;/div&gt;&lt;br&gt;&lt;div&gt;&lt;font style=&quot;font-size: 11px&quot;&gt;&lt;font color=&quot;#cccccc&quot;&gt;%c4Description%&lt;/font&gt;&lt;/div&gt;" id="WMC1f1DDedSoK6EWAYH4-0">
          <mxCell parent="1n15_pKxOORiXK8SXrbd-1" style="html=1;fontSize=11;dashed=0;whiteSpace=wrap;fillColor=#083F75;strokeColor=#06315C;fontColor=#ffffff;shape=mxgraph.c4.person2;align=center;metaEdit=1;points=[[0.5,0,0],[1,0.5,0],[1,0.75,0],[0.75,1,0],[0.5,1,0],[0.25,1,0],[0,0.75,0],[0,0.5,0]];resizable=0;" vertex="1">
            <mxGeometry height="180" width="200" x="270" y="220" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Name="BancoLitoral" c4Type="WAR" c4Technology="Java" c4Description="Sistema Web Interno" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;%c4Name%&lt;/b&gt;&lt;/font&gt;&lt;div&gt;[%c4Type%:&amp;nbsp;%c4Technology%]&lt;/div&gt;&lt;br&gt;&lt;div&gt;&lt;font style=&quot;font-size: 11px&quot;&gt;&lt;font color=&quot;#E6E6E6&quot;&gt;%c4Description%&lt;/font&gt;&lt;/div&gt;" id="WMC1f1DDedSoK6EWAYH4-3">
          <mxCell parent="1n15_pKxOORiXK8SXrbd-1" style="shape=mxgraph.c4.webBrowserContainer2;whiteSpace=wrap;html=1;boundedLbl=1;rounded=0;labelBackgroundColor=none;strokeColor=#118ACD;fillColor=#23A2D9;strokeColor=#118ACD;strokeColor2=#0E7DAD;fontSize=12;fontColor=#ffffff;align=center;metaEdit=1;points=[[0.5,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.5,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];resizable=0;" vertex="1">
            <mxGeometry height="160" width="240" x="640" y="230" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Name="Exchange365" c4Type="Software System" c4Description="Servicio de Notificaciones de MS365" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;%c4Name%&lt;/b&gt;&lt;/font&gt;&lt;div&gt;[%c4Type%]&lt;/div&gt;&lt;br&gt;&lt;div&gt;&lt;font style=&quot;font-size: 11px&quot;&gt;&lt;font color=&quot;#cccccc&quot;&gt;%c4Description%&lt;/font&gt;&lt;/div&gt;" id="ZhOa4PEXIP64QEeNXCD0-0">
          <mxCell parent="1n15_pKxOORiXK8SXrbd-1" style="rounded=1;whiteSpace=wrap;html=1;labelBackgroundColor=none;fillColor=#8C8496;fontColor=#ffffff;align=center;arcSize=10;strokeColor=#736782;metaEdit=1;resizable=0;points=[[0.25,0,0],[0.5,0,0],[0.75,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.75,1,0],[0.5,1,0],[0.25,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];" vertex="1">
            <mxGeometry height="120" width="240" x="1360" y="250" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Name="Oracle Database 12" c4Type="Esquema" c4Technology="PRODUCTO_SERVICIO" c4Description="Almacenar información del sistema" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;%c4Name%&lt;/b&gt;&lt;/font&gt;&lt;div&gt;[%c4Type%:&amp;nbsp;%c4Technology%]&lt;/div&gt;&lt;br&gt;&lt;div&gt;&lt;font style=&quot;font-size: 11px&quot;&gt;&lt;font color=&quot;#E6E6E6&quot;&gt;%c4Description%&lt;/font&gt;&lt;/div&gt;" id="AfENbaElDomVsFHvtgEs-0">
          <mxCell parent="1n15_pKxOORiXK8SXrbd-1" style="shape=cylinder3;size=15;whiteSpace=wrap;html=1;boundedLbl=1;rounded=0;labelBackgroundColor=none;fillColor=#23A2D9;fontSize=12;fontColor=#ffffff;align=center;strokeColor=#0E7DAD;metaEdit=1;points=[[0.5,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.5,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];resizable=0;" vertex="1">
            <mxGeometry height="120" width="240" x="960" y="540" as="geometry" />
          </mxCell>
        </object>
        <mxCell id="I9fNkN6Fc--YZo9XAbdK-0" edge="1" parent="1n15_pKxOORiXK8SXrbd-1" source="I9fNkN6Fc--YZo9XAbdK-7" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;exitX=0.5;exitY=1;exitDx=0;exitDy=0;exitPerimeter=0;entryX=0.5;entryY=0;entryDx=0;entryDy=0;entryPerimeter=0;" target="AfENbaElDomVsFHvtgEs-0">
          <mxGeometry relative="1" as="geometry">
            <mxPoint x="1080" y="370" as="sourcePoint" />
          </mxGeometry>
        </mxCell>
        <mxCell id="I9fNkN6Fc--YZo9XAbdK-1" edge="1" parent="1n15_pKxOORiXK8SXrbd-1" source="I9fNkN6Fc--YZo9XAbdK-7" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;entryX=0;entryY=0.5;entryDx=0;entryDy=0;entryPerimeter=0;exitX=1;exitY=0.5;exitDx=0;exitDy=0;exitPerimeter=0;" target="ZhOa4PEXIP64QEeNXCD0-0">
          <mxGeometry relative="1" as="geometry">
            <mxPoint x="1200" y="310" as="sourcePoint" />
          </mxGeometry>
        </mxCell>
        <mxCell id="I9fNkN6Fc--YZo9XAbdK-2" edge="1" parent="1n15_pKxOORiXK8SXrbd-1" source="WMC1f1DDedSoK6EWAYH4-3" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;exitX=1;exitY=0.5;exitDx=0;exitDy=0;exitPerimeter=0;entryX=0;entryY=0.5;entryDx=0;entryDy=0;entryPerimeter=0;" target="I9fNkN6Fc--YZo9XAbdK-7">
          <mxGeometry relative="1" as="geometry">
            <mxPoint x="960" y="310" as="targetPoint" />
          </mxGeometry>
        </mxCell>
        <object placeholders="1" c4Name="Wildfly v10" c4Type="Java" c4Application="Software System" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;&lt;div style=&quot;text-align: left&quot;&gt;%c4Name%&lt;/div&gt;&lt;/b&gt;&lt;/font&gt;&lt;div style=&quot;text-align: left&quot;&gt;[%c4Application%]&lt;/div&gt;" id="I9fNkN6Fc--YZo9XAbdK-4">
          <mxCell parent="1n15_pKxOORiXK8SXrbd-1" style="rounded=1;fontSize=11;whiteSpace=wrap;html=1;dashed=1;arcSize=20;fillColor=none;strokeColor=#666666;fontColor=#333333;labelBackgroundColor=none;align=left;verticalAlign=bottom;labelBorderColor=none;spacingTop=0;spacing=10;dashPattern=8 4;metaEdit=1;rotatable=0;perimeter=rectanglePerimeter;noLabel=0;labelPadding=0;allowArrows=0;connectable=0;expand=0;recursiveResize=0;editable=1;pointerEvents=0;absoluteArcSize=1;points=[[0.25,0,0],[0.5,0,0],[0.75,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.75,1,0],[0.5,1,0],[0.25,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];" vertex="1">
            <mxGeometry height="290" width="720" x="560" y="170" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Name="BL.APP.RRHH" c4Type="API" c4Technology="Java" c4Description="Módulo de gestion de RR.HH" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;%c4Name%&lt;/b&gt;&lt;/font&gt;&lt;div&gt;[%c4Type%:&amp;nbsp;%c4Technology%]&lt;/div&gt;&lt;br&gt;&lt;div&gt;&lt;font style=&quot;font-size: 11px&quot;&gt;&lt;font color=&quot;#E6E6E6&quot;&gt;%c4Description%&lt;/font&gt;&lt;/div&gt;" id="I9fNkN6Fc--YZo9XAbdK-7">
          <mxCell parent="1n15_pKxOORiXK8SXrbd-1" style="shape=hexagon;size=50;perimeter=hexagonPerimeter2;whiteSpace=wrap;html=1;fixedSize=1;rounded=1;labelBackgroundColor=none;fillColor=#23A2D9;fontSize=12;fontColor=#ffffff;align=center;strokeColor=#0E7DAD;metaEdit=1;points=[[0.5,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.5,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];resizable=0;" vertex="1">
            <mxGeometry height="170" width="200" x="980" y="225" as="geometry" />
          </mxCell>
        </object>
      </root>
    </mxGraphModel>
  </diagram>
  <diagram id="S4n5isgT4MQJhM72Ye09" name="Diagrama de componentes">
    <mxGraphModel dx="2206" dy="888" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="827" pageHeight="1169" math="0" shadow="0">
      <root>
        <mxCell id="0" />
        <mxCell id="1" parent="0" />
        <object placeholders="1" c4Name="BancoLitoral" c4Type="WAR" c4Technology="WS" c4Description="Sistema Web Interno" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;%c4Name%&lt;/b&gt;&lt;/font&gt;&lt;div&gt;[%c4Type%:&amp;nbsp;%c4Technology%]&lt;/div&gt;&lt;br&gt;&lt;div&gt;&lt;font style=&quot;font-size: 11px&quot;&gt;&lt;font color=&quot;#E6E6E6&quot;&gt;%c4Description%&lt;/font&gt;&lt;/div&gt;" id="7FHuSbBK_qWsFP_E98WO-1">
          <mxCell parent="1" style="shape=mxgraph.c4.webBrowserContainer2;whiteSpace=wrap;html=1;boundedLbl=1;rounded=0;labelBackgroundColor=none;strokeColor=#118ACD;fillColor=#23A2D9;strokeColor=#118ACD;strokeColor2=#0E7DAD;fontSize=12;fontColor=#ffffff;align=center;metaEdit=1;points=[[0.5,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.5,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];resizable=0;" vertex="1">
            <mxGeometry height="160" width="240" x="710" y="160" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Name="Exchange365" c4Type="Software System" c4Description="Servicio de Notificaciones de MS365" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;%c4Name%&lt;/b&gt;&lt;/font&gt;&lt;div&gt;[%c4Type%]&lt;/div&gt;&lt;br&gt;&lt;div&gt;&lt;font style=&quot;font-size: 11px&quot;&gt;&lt;font color=&quot;#cccccc&quot;&gt;%c4Description%&lt;/font&gt;&lt;/div&gt;" id="AFJHnL__RS9t1kb_xQMW-1">
          <mxCell parent="1" style="rounded=1;whiteSpace=wrap;html=1;labelBackgroundColor=none;fillColor=#8C8496;fontColor=#ffffff;align=center;arcSize=10;strokeColor=#736782;metaEdit=1;resizable=0;points=[[0.25,0,0],[0.5,0,0],[0.75,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.75,1,0],[0.5,1,0],[0.25,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];" vertex="1">
            <mxGeometry height="120" width="240" x="1100" y="1360" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Name="PutFormularioCSE" c4Type="Component" c4Technology="RestController" c4Description="" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;%c4Name%&lt;/b&gt;&lt;/font&gt;&lt;div&gt;[%c4Type%: %c4Technology%]&lt;/div&gt;&lt;br&gt;&lt;div&gt;&lt;font style=&quot;font-size: 11px&quot;&gt;%c4Description%&lt;/font&gt;&lt;/div&gt;" id="AFJHnL__RS9t1kb_xQMW-7">
          <mxCell parent="1" style="rounded=1;whiteSpace=wrap;html=1;labelBackgroundColor=none;fillColor=#63BEF2;fontColor=#ffffff;align=center;arcSize=6;strokeColor=#2086C9;metaEdit=1;resizable=0;points=[[0.25,0,0],[0.5,0,0],[0.75,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.75,1,0],[0.5,1,0],[0.25,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];" vertex="1">
            <mxGeometry height="120" width="240" x="460" y="480" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Name="ActualizarFormularioCSE" c4Type="Component" c4Technology="Service" c4Description="" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;%c4Name%&lt;/b&gt;&lt;/font&gt;&lt;div&gt;[%c4Type%: %c4Technology%]&lt;/div&gt;&lt;br&gt;&lt;div&gt;&lt;font style=&quot;font-size: 11px&quot;&gt;%c4Description%&lt;/font&gt;&lt;/div&gt;" id="AFJHnL__RS9t1kb_xQMW-12">
          <mxCell parent="1" style="rounded=1;whiteSpace=wrap;html=1;labelBackgroundColor=none;fillColor=#fff2cc;align=center;arcSize=6;strokeColor=#d6b656;metaEdit=1;resizable=0;points=[[0.25,0,0],[0.5,0,0],[0.75,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.75,1,0],[0.5,1,0],[0.25,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];" vertex="1">
            <mxGeometry height="120" width="240" x="460" y="680" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Type="Relationship" id="AFJHnL__RS9t1kb_xQMW-16">
          <mxCell edge="1" parent="1" source="AFJHnL__RS9t1kb_xQMW-7" style="endArrow=blockThin;html=1;fontSize=10;fontColor=#404040;strokeWidth=1;endFill=1;strokeColor=#828282;elbow=vertical;metaEdit=1;endSize=14;startSize=14;jumpStyle=arc;jumpSize=16;rounded=0;edgeStyle=orthogonalEdgeStyle;exitX=0.5;exitY=1;exitDx=0;exitDy=0;exitPerimeter=0;entryX=0.5;entryY=0;entryDx=0;entryDy=0;entryPerimeter=0;" target="AFJHnL__RS9t1kb_xQMW-12">
            <mxGeometry relative="1" width="240" as="geometry">
              <mxPoint x="530" y="730" as="sourcePoint" />
              <mxPoint x="770" y="730" as="targetPoint" />
            </mxGeometry>
          </mxCell>
        </object>
        <object placeholders="1" c4Name="GetFormularioCSE" c4Type="Component" c4Technology="RestController" c4Description="" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;%c4Name%&lt;/b&gt;&lt;/font&gt;&lt;div&gt;[%c4Type%: %c4Technology%]&lt;/div&gt;&lt;br&gt;&lt;div&gt;&lt;font style=&quot;font-size: 11px&quot;&gt;%c4Description%&lt;/font&gt;&lt;/div&gt;" id="AFJHnL__RS9t1kb_xQMW-19">
          <mxCell parent="1" style="rounded=1;whiteSpace=wrap;html=1;labelBackgroundColor=none;fillColor=#63BEF2;fontColor=#ffffff;align=center;arcSize=6;strokeColor=#2086C9;metaEdit=1;resizable=0;points=[[0.25,0,0],[0.5,0,0],[0.75,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.75,1,0],[0.5,1,0],[0.25,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];" vertex="1">
            <mxGeometry height="120" width="240" x="781" y="480" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Name="ObtenerFormularioCSE" c4Type="Component" c4Technology="Service" c4Description="" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;%c4Name%&lt;/b&gt;&lt;/font&gt;&lt;div&gt;[%c4Type%: %c4Technology%]&lt;/div&gt;&lt;br&gt;&lt;div&gt;&lt;font style=&quot;font-size: 11px&quot;&gt;%c4Description%&lt;/font&gt;&lt;/div&gt;" id="AFJHnL__RS9t1kb_xQMW-21">
          <mxCell parent="1" style="rounded=1;whiteSpace=wrap;html=1;labelBackgroundColor=none;fillColor=#fff2cc;align=center;arcSize=6;strokeColor=#d6b656;metaEdit=1;resizable=0;points=[[0.25,0,0],[0.5,0,0],[0.75,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.75,1,0],[0.5,1,0],[0.25,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];" vertex="1">
            <mxGeometry height="120" width="240" x="781" y="680" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Type="Relationship" id="AFJHnL__RS9t1kb_xQMW-22">
          <mxCell edge="1" parent="1" source="AFJHnL__RS9t1kb_xQMW-19" style="endArrow=blockThin;html=1;fontSize=10;fontColor=#404040;strokeWidth=1;endFill=1;strokeColor=#828282;elbow=vertical;metaEdit=1;endSize=14;startSize=14;jumpStyle=arc;jumpSize=16;rounded=0;edgeStyle=orthogonalEdgeStyle;exitX=0.5;exitY=1;exitDx=0;exitDy=0;exitPerimeter=0;entryX=0.5;entryY=0;entryDx=0;entryDy=0;entryPerimeter=0;" target="AFJHnL__RS9t1kb_xQMW-21">
            <mxGeometry relative="1" width="240" as="geometry">
              <mxPoint x="810" y="880" as="sourcePoint" />
              <mxPoint x="1050" y="880" as="targetPoint" />
            </mxGeometry>
          </mxCell>
        </object>
        <object placeholders="1" c4Name="Notify" c4Type="Component" c4Technology="Service" c4Description="" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;%c4Name%&lt;/b&gt;&lt;/font&gt;&lt;div&gt;[%c4Type%: %c4Technology%]&lt;/div&gt;&lt;br&gt;&lt;div&gt;&lt;font style=&quot;font-size: 11px&quot;&gt;%c4Description%&lt;/font&gt;&lt;/div&gt;" id="AFJHnL__RS9t1kb_xQMW-24">
          <mxCell parent="1" style="rounded=1;whiteSpace=wrap;html=1;labelBackgroundColor=none;fillColor=#fff2cc;align=center;arcSize=6;strokeColor=#d6b656;metaEdit=1;resizable=0;points=[[0.25,0,0],[0.5,0,0],[0.75,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.75,1,0],[0.5,1,0],[0.25,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];" vertex="1">
            <mxGeometry height="120" width="240" x="1100" y="680" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Name="FormularioCSE" c4Type="Component" c4Technology="Repository" c4Description="" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;%c4Name%&lt;/b&gt;&lt;/font&gt;&lt;div&gt;[%c4Type%: %c4Technology%]&lt;/div&gt;&lt;br&gt;&lt;div&gt;&lt;font style=&quot;font-size: 11px&quot;&gt;%c4Description%&lt;/font&gt;&lt;/div&gt;" id="AFJHnL__RS9t1kb_xQMW-25">
          <mxCell parent="1" style="rounded=1;whiteSpace=wrap;html=1;labelBackgroundColor=none;fillColor=#e1d5e7;align=center;arcSize=6;strokeColor=#9673a6;metaEdit=1;resizable=0;points=[[0.25,0,0],[0.5,0,0],[0.75,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.75,1,0],[0.5,1,0],[0.25,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];" vertex="1">
            <mxGeometry height="120" width="240" x="460" y="880" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Type="Relationship" id="AFJHnL__RS9t1kb_xQMW-29">
          <mxCell edge="1" parent="1" source="AFJHnL__RS9t1kb_xQMW-12" style="endArrow=blockThin;html=1;fontSize=10;fontColor=#404040;strokeWidth=1;endFill=1;strokeColor=#828282;elbow=vertical;metaEdit=1;endSize=14;startSize=14;jumpStyle=arc;jumpSize=16;rounded=0;edgeStyle=orthogonalEdgeStyle;exitX=0.25;exitY=1;exitDx=0;exitDy=0;exitPerimeter=0;entryX=0.25;entryY=0;entryDx=0;entryDy=0;entryPerimeter=0;" target="AFJHnL__RS9t1kb_xQMW-25">
            <mxGeometry relative="1" width="240" as="geometry">
              <mxPoint x="380" y="880" as="sourcePoint" />
              <mxPoint x="620" y="880" as="targetPoint" />
            </mxGeometry>
          </mxCell>
        </object>
        <mxCell id="jHCnB6F18MAmHVPDIs_y-21" connectable="0" parent="AFJHnL__RS9t1kb_xQMW-29" style="edgeLabel;html=1;align=center;verticalAlign=middle;resizable=0;points=[];" value="1. Actualiza" vertex="1">
          <mxGeometry relative="1" x="-0.0036" as="geometry">
            <mxPoint as="offset" />
          </mxGeometry>
        </mxCell>
        <object placeholders="1" c4Type="Relationship" id="AFJHnL__RS9t1kb_xQMW-37">
          <mxCell edge="1" parent="1" source="7FHuSbBK_qWsFP_E98WO-1" style="endArrow=blockThin;html=1;fontSize=10;fontColor=#404040;strokeWidth=1;endFill=1;strokeColor=#828282;elbow=vertical;metaEdit=1;endSize=14;startSize=14;jumpStyle=arc;jumpSize=16;rounded=0;edgeStyle=orthogonalEdgeStyle;exitX=0.5;exitY=1;exitDx=0;exitDy=0;exitPerimeter=0;">
            <mxGeometry relative="1" width="240" as="geometry">
              <mxPoint x="650" y="250" as="sourcePoint" />
              <mxPoint x="830" y="400" as="targetPoint" />
            </mxGeometry>
          </mxCell>
        </object>
        <object placeholders="1" c4Name="BL.APP.RRHH" c4Type="ContainerScopeBoundary" c4Application="192.168.100.0/24" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;&lt;div style=&quot;text-align: left&quot;&gt;%c4Name%&lt;/div&gt;&lt;/b&gt;&lt;/font&gt;&lt;div style=&quot;text-align: left&quot;&gt;[%c4Application%]&lt;/div&gt;" id="jHCnB6F18MAmHVPDIs_y-2">
          <mxCell parent="1" style="rounded=1;fontSize=11;whiteSpace=wrap;html=1;dashed=1;arcSize=20;fillColor=none;strokeColor=#666666;fontColor=#333333;labelBackgroundColor=none;align=left;verticalAlign=bottom;labelBorderColor=none;spacingTop=0;spacing=10;dashPattern=8 4;metaEdit=1;rotatable=0;perimeter=rectanglePerimeter;noLabel=0;labelPadding=0;allowArrows=0;connectable=0;expand=0;recursiveResize=0;editable=1;pointerEvents=0;absoluteArcSize=1;points=[[0.25,0,0],[0.5,0,0],[0.75,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.75,1,0],[0.5,1,0],[0.25,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];" vertex="1">
            <mxGeometry height="880" width="1110" x="310" y="400" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Type="Relationship" c4Description="2. Notifica la actualización" label="&lt;div style=&quot;text-align: left&quot;&gt;&lt;div style=&quot;text-align: center&quot;&gt;&lt;b&gt;%c4Description%&lt;/b&gt;&lt;/div&gt;" id="jHCnB6F18MAmHVPDIs_y-5">
          <mxCell edge="1" parent="1" source="AFJHnL__RS9t1kb_xQMW-12" style="endArrow=blockThin;html=1;fontSize=10;fontColor=#404040;strokeWidth=1;endFill=1;strokeColor=#828282;elbow=vertical;metaEdit=1;endSize=14;startSize=14;jumpStyle=arc;jumpSize=16;rounded=0;edgeStyle=orthogonalEdgeStyle;exitX=0.75;exitY=1;exitDx=0;exitDy=0;exitPerimeter=0;entryX=0.25;entryY=1;entryDx=0;entryDy=0;entryPerimeter=0;" target="AFJHnL__RS9t1kb_xQMW-24">
            <mxGeometry relative="1" width="240" as="geometry">
              <Array as="points">
                <mxPoint x="640" y="860" />
                <mxPoint x="1160" y="860" />
              </Array>
              <mxPoint x="950" y="840" as="sourcePoint" />
              <mxPoint x="1190" y="840" as="targetPoint" />
            </mxGeometry>
          </mxCell>
        </object>
        <object placeholders="1" c4Name="OracleConexion" c4Type="Drive" c4Technology="JDBC" c4Description="" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;%c4Name%&lt;/b&gt;&lt;/font&gt;&lt;div&gt;[%c4Type%: %c4Technology%]&lt;/div&gt;&lt;br&gt;&lt;div&gt;&lt;font style=&quot;font-size: 11px&quot;&gt;%c4Description%&lt;/font&gt;&lt;/div&gt;" id="jHCnB6F18MAmHVPDIs_y-9">
          <mxCell parent="1" style="rounded=1;whiteSpace=wrap;html=1;labelBackgroundColor=none;fillColor=#63BEF2;fontColor=#ffffff;align=center;arcSize=6;strokeColor=#2086C9;metaEdit=1;resizable=0;points=[[0.25,0,0],[0.5,0,0],[0.75,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.75,1,0],[0.5,1,0],[0.25,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];" vertex="1">
            <mxGeometry height="120" width="240" x="460" y="1080" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Type="Relationship" id="jHCnB6F18MAmHVPDIs_y-10">
          <mxCell edge="1" parent="1" source="AFJHnL__RS9t1kb_xQMW-25" style="endArrow=blockThin;html=1;fontSize=10;fontColor=#404040;strokeWidth=1;endFill=1;strokeColor=#828282;elbow=vertical;metaEdit=1;endSize=14;startSize=14;jumpStyle=arc;jumpSize=16;rounded=0;edgeStyle=orthogonalEdgeStyle;exitX=0.5;exitY=1;exitDx=0;exitDy=0;exitPerimeter=0;entryX=0.5;entryY=0;entryDx=0;entryDy=0;entryPerimeter=0;" target="jHCnB6F18MAmHVPDIs_y-9">
            <mxGeometry relative="1" width="240" as="geometry">
              <mxPoint x="640" y="1100" as="sourcePoint" />
              <mxPoint x="880" y="1100" as="targetPoint" />
            </mxGeometry>
          </mxCell>
        </object>
        <object placeholders="1" c4Type="Relationship" c4Description="Envia Correo" label="&lt;div style=&quot;text-align: left&quot;&gt;&lt;div style=&quot;text-align: center&quot;&gt;&lt;b&gt;%c4Description%&lt;/b&gt;&lt;/div&gt;" id="jHCnB6F18MAmHVPDIs_y-13">
          <mxCell edge="1" parent="1" source="AFJHnL__RS9t1kb_xQMW-24" style="endArrow=blockThin;html=1;fontSize=10;fontColor=#404040;strokeWidth=1;endFill=1;strokeColor=#828282;elbow=vertical;metaEdit=1;endSize=14;startSize=14;jumpStyle=arc;jumpSize=16;rounded=0;edgeStyle=orthogonalEdgeStyle;exitX=0.5;exitY=1;exitDx=0;exitDy=0;exitPerimeter=0;entryX=0.5;entryY=0;entryDx=0;entryDy=0;entryPerimeter=0;" target="AFJHnL__RS9t1kb_xQMW-1">
            <mxGeometry relative="1" width="240" as="geometry">
              <mxPoint x="640" y="1100" as="sourcePoint" />
              <mxPoint x="880" y="1100" as="targetPoint" />
            </mxGeometry>
          </mxCell>
        </object>
        <object placeholders="1" c4Name="UserSystem" c4Type="Component" c4Technology="Repository" c4Description="" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;%c4Name%&lt;/b&gt;&lt;/font&gt;&lt;div&gt;[%c4Type%: %c4Technology%]&lt;/div&gt;&lt;br&gt;&lt;div&gt;&lt;font style=&quot;font-size: 11px&quot;&gt;%c4Description%&lt;/font&gt;&lt;/div&gt;" id="jHCnB6F18MAmHVPDIs_y-14">
          <mxCell parent="1" style="rounded=1;whiteSpace=wrap;html=1;labelBackgroundColor=none;fillColor=#e1d5e7;align=center;arcSize=6;strokeColor=#9673a6;metaEdit=1;resizable=0;points=[[0.25,0,0],[0.5,0,0],[0.75,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.75,1,0],[0.5,1,0],[0.25,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];" vertex="1">
            <mxGeometry height="120" width="240" x="781" y="880" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Type="Relationship" id="jHCnB6F18MAmHVPDIs_y-15">
          <mxCell edge="1" parent="1" source="jHCnB6F18MAmHVPDIs_y-14" style="endArrow=blockThin;html=1;fontSize=10;fontColor=#404040;strokeWidth=1;endFill=1;strokeColor=#828282;elbow=vertical;metaEdit=1;endSize=14;startSize=14;jumpStyle=arc;jumpSize=16;rounded=0;edgeStyle=orthogonalEdgeStyle;exitX=0.5;exitY=1;exitDx=0;exitDy=0;exitPerimeter=0;entryX=1;entryY=0.5;entryDx=0;entryDy=0;entryPerimeter=0;" target="jHCnB6F18MAmHVPDIs_y-9">
            <mxGeometry relative="1" width="240" as="geometry">
              <mxPoint x="910" y="1060" as="sourcePoint" />
              <mxPoint x="1150" y="1060" as="targetPoint" />
            </mxGeometry>
          </mxCell>
        </object>
        <object placeholders="1" c4Type="Relationship" c4Description="1. Busca Usuario" label="&lt;div style=&quot;text-align: left&quot;&gt;&lt;div style=&quot;text-align: center&quot;&gt;&lt;b&gt;%c4Description%&lt;/b&gt;&lt;/div&gt;" id="jHCnB6F18MAmHVPDIs_y-18">
          <mxCell edge="1" parent="1" source="AFJHnL__RS9t1kb_xQMW-21" style="endArrow=blockThin;html=1;fontSize=10;fontColor=#404040;strokeWidth=1;endFill=1;strokeColor=#828282;elbow=vertical;metaEdit=1;endSize=14;startSize=14;jumpStyle=arc;jumpSize=16;rounded=0;edgeStyle=orthogonalEdgeStyle;exitX=1;exitY=0.75;exitDx=0;exitDy=0;exitPerimeter=0;entryX=1;entryY=0.25;entryDx=0;entryDy=0;entryPerimeter=0;" target="jHCnB6F18MAmHVPDIs_y-14">
            <mxGeometry relative="1" width="240" as="geometry">
              <Array as="points">
                <mxPoint x="1060" y="770" />
                <mxPoint x="1060" y="910" />
              </Array>
              <mxPoint x="990" y="910" as="sourcePoint" />
              <mxPoint x="1020" y="970" as="targetPoint" />
            </mxGeometry>
          </mxCell>
        </object>
        <object placeholders="1" c4Type="Relationship" c4Description="2. Busca formularario CSE" label="&lt;div style=&quot;text-align: left&quot;&gt;&lt;div style=&quot;text-align: center&quot;&gt;&lt;b&gt;%c4Description%&lt;/b&gt;&lt;/div&gt;" id="jHCnB6F18MAmHVPDIs_y-20">
          <mxCell edge="1" parent="1" source="AFJHnL__RS9t1kb_xQMW-21" style="endArrow=blockThin;html=1;fontSize=10;fontColor=#404040;strokeWidth=1;endFill=1;strokeColor=#828282;elbow=vertical;metaEdit=1;endSize=14;startSize=14;jumpStyle=arc;jumpSize=16;rounded=0;edgeStyle=orthogonalEdgeStyle;exitX=0;exitY=0.75;exitDx=0;exitDy=0;exitPerimeter=0;entryX=1;entryY=0.25;entryDx=0;entryDy=0;entryPerimeter=0;" target="AFJHnL__RS9t1kb_xQMW-25">
            <mxGeometry relative="1" width="240" as="geometry">
              <mxPoint x="640" y="910" as="sourcePoint" />
              <mxPoint x="880" y="910" as="targetPoint" />
            </mxGeometry>
          </mxCell>
        </object>
        <object placeholders="1" c4Name="Oracle Database v12" c4Type="SystemScopeBoundary" c4Application="192.168.100.0/24" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;&lt;div style=&quot;text-align: left&quot;&gt;%c4Name%&lt;/div&gt;&lt;/b&gt;&lt;/font&gt;&lt;div style=&quot;text-align: left&quot;&gt;[%c4Application%]&lt;/div&gt;" id="us3H26R-JtF5iCCMwxby-1">
          <mxCell parent="1" style="rounded=1;fontSize=11;whiteSpace=wrap;html=1;dashed=1;arcSize=20;fillColor=none;strokeColor=#666666;fontColor=#333333;labelBackgroundColor=none;align=left;verticalAlign=bottom;labelBorderColor=none;spacingTop=0;spacing=10;dashPattern=8 4;metaEdit=1;rotatable=0;perimeter=rectanglePerimeter;noLabel=0;labelPadding=0;allowArrows=0;connectable=0;expand=0;recursiveResize=0;editable=1;pointerEvents=0;absoluteArcSize=1;points=[[0.25,0,0],[0.5,0,0],[0.75,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.75,1,0],[0.5,1,0],[0.25,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];" vertex="1">
            <mxGeometry height="440" width="560" x="120" y="1360" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Name="PRODUCTO_SERVICIO" c4Type="ESCHEMA" c4Application="ESQUEMA" label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;&lt;div style=&quot;text-align: left&quot;&gt;%c4Name%&lt;/div&gt;&lt;/b&gt;&lt;/font&gt;&lt;div style=&quot;text-align: left&quot;&gt;[%c4Application%]&lt;/div&gt;" id="us3H26R-JtF5iCCMwxby-2">
          <mxCell parent="1" style="rounded=1;fontSize=11;whiteSpace=wrap;html=1;dashed=1;arcSize=20;fillColor=none;strokeColor=#666666;fontColor=#333333;labelBackgroundColor=none;align=left;verticalAlign=bottom;labelBorderColor=none;spacingTop=0;spacing=10;dashPattern=8 4;metaEdit=1;rotatable=0;perimeter=rectanglePerimeter;noLabel=0;labelPadding=0;allowArrows=0;connectable=0;expand=0;recursiveResize=0;editable=1;pointerEvents=0;absoluteArcSize=1;points=[[0.25,0,0],[0.5,0,0],[0.75,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.75,1,0],[0.5,1,0],[0.25,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];" vertex="1">
            <mxGeometry height="280" width="400" x="200" y="1440" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Name="PKG_RRHH_FORMULARIO_CSE" c4Type="PACKAGE" c4Technology="" c4Description="Description of component role/responsibility." label="&lt;font style=&quot;font-size: 16px&quot;&gt;&lt;b&gt;%c4Name%&lt;/b&gt;&lt;/font&gt;&lt;div&gt;[%c4Type%: %c4Technology%]&lt;/div&gt;&lt;br&gt;&lt;div&gt;&lt;font style=&quot;font-size: 11px&quot;&gt;%c4Description%&lt;/font&gt;&lt;/div&gt;" id="us3H26R-JtF5iCCMwxby-3">
          <mxCell parent="1" style="rounded=1;whiteSpace=wrap;html=1;labelBackgroundColor=none;fillColor=#63BEF2;fontColor=#ffffff;align=center;arcSize=6;strokeColor=#2086C9;metaEdit=1;resizable=0;points=[[0.25,0,0],[0.5,0,0],[0.75,0,0],[1,0.25,0],[1,0.5,0],[1,0.75,0],[0.75,1,0],[0.5,1,0],[0.25,1,0],[0,0.75,0],[0,0.5,0],[0,0.25,0]];" vertex="1">
            <mxGeometry height="120" width="240" x="280" y="1514" as="geometry" />
          </mxCell>
        </object>
        <object placeholders="1" c4Type="Relationship" id="us3H26R-JtF5iCCMwxby-6">
          <mxCell edge="1" parent="1" source="jHCnB6F18MAmHVPDIs_y-9" style="endArrow=blockThin;html=1;fontSize=10;fontColor=#404040;strokeWidth=1;endFill=1;strokeColor=#828282;elbow=vertical;metaEdit=1;endSize=14;startSize=14;jumpStyle=arc;jumpSize=16;rounded=0;edgeStyle=orthogonalEdgeStyle;exitX=0.5;exitY=1;exitDx=0;exitDy=0;exitPerimeter=0;">
            <mxGeometry relative="1" width="240" as="geometry">
              <mxPoint x="240" y="1200" as="sourcePoint" />
              <mxPoint x="580" y="1440" as="targetPoint" />
            </mxGeometry>
          </mxCell>
        </object>
        <object placeholders="1" c4Type="Relationship" id="us3H26R-JtF5iCCMwxby-7">
          <mxCell edge="1" parent="1" source="AFJHnL__RS9t1kb_xQMW-25" style="endArrow=blockThin;html=1;fontSize=10;fontColor=#404040;strokeWidth=1;endFill=1;strokeColor=#828282;elbow=vertical;metaEdit=1;endSize=14;startSize=14;jumpStyle=arc;jumpSize=16;rounded=0;edgeStyle=orthogonalEdgeStyle;exitX=0;exitY=0.5;exitDx=0;exitDy=0;exitPerimeter=0;">
            <mxGeometry relative="1" width="240" as="geometry">
              <mxPoint x="240" y="1200" as="sourcePoint" />
              <mxPoint x="400" y="1510" as="targetPoint" />
            </mxGeometry>
          </mxCell>
        </object>
      </root>
    </mxGraphModel>
  </diagram>
  <diagram id="Y03dX3tK0UPymg7trVYm" name="Diagrama de clases">
    <mxGraphModel dx="3083" dy="1269" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="827" pageHeight="1169" math="0" shadow="0">
      <root>
        <mxCell id="0" />
        <mxCell id="1" parent="0" />
        <mxCell id="fYSa4BK9EUfcGU9cp0zs-24" parent="1" style="swimlane;fontStyle=0;align=center;verticalAlign=top;childLayout=stackLayout;horizontal=1;startSize=55;horizontalStack=0;resizeParent=1;resizeParentMax=0;resizeLast=0;collapsible=0;marginBottom=0;html=1;whiteSpace=wrap;" value="&lt;br&gt;&lt;b&gt;PutFormularioCSERestController&lt;/b&gt;&lt;div&gt;&lt;br/&gt;&lt;/div&gt;" vertex="1">
          <mxGeometry height="163" width="270" x="190" y="270" as="geometry" />
        </mxCell>
        <mxCell id="fYSa4BK9EUfcGU9cp0zs-25" parent="fYSa4BK9EUfcGU9cp0zs-24" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="attributes" vertex="1">
          <mxGeometry height="20" width="270" y="55" as="geometry" />
        </mxCell>
        <mxCell id="fYSa4BK9EUfcGU9cp0zs-26" parent="fYSa4BK9EUfcGU9cp0zs-24" style="text;html=1;strokeColor=none;fillColor=none;align=left;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="ActualizarFormularioCSEService service" vertex="1">
          <mxGeometry height="20" width="270" y="75" as="geometry" />
        </mxCell>
        <mxCell id="fYSa4BK9EUfcGU9cp0zs-28" parent="fYSa4BK9EUfcGU9cp0zs-24" style="text;html=1;strokeColor=none;fillColor=none;align=left;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="..." vertex="1">
          <mxGeometry height="20" width="270" y="95" as="geometry" />
        </mxCell>
        <mxCell id="fYSa4BK9EUfcGU9cp0zs-29" parent="fYSa4BK9EUfcGU9cp0zs-24" style="line;strokeWidth=1;fillColor=none;align=left;verticalAlign=middle;spacingTop=-1;spacingLeft=3;spacingRight=3;rotatable=0;labelPosition=right;points=[];portConstraint=eastwest;" value="" vertex="1">
          <mxGeometry height="8" width="270" y="115" as="geometry" />
        </mxCell>
        <mxCell id="fYSa4BK9EUfcGU9cp0zs-30" parent="fYSa4BK9EUfcGU9cp0zs-24" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="operations" vertex="1">
          <mxGeometry height="20" width="270" y="123" as="geometry" />
        </mxCell>
        <mxCell id="fYSa4BK9EUfcGU9cp0zs-31" parent="fYSa4BK9EUfcGU9cp0zs-24" style="text;html=1;strokeColor=none;fillColor=none;align=left;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="update(FormularioCSE formulario)" vertex="1">
          <mxGeometry height="20" width="270" y="143" as="geometry" />
        </mxCell>
        <mxCell id="nfsdQfqAbzpklse4fwm_-1" parent="1" style="swimlane;fontStyle=0;align=center;verticalAlign=top;childLayout=stackLayout;horizontal=1;startSize=55;horizontalStack=0;resizeParent=1;resizeParentMax=0;resizeLast=0;collapsible=0;marginBottom=0;html=1;whiteSpace=wrap;" value="&lt;br&gt;&lt;span style=&quot;text-align: left;&quot;&gt;&lt;b&gt;ActualizarFormularioCSEService&lt;/b&gt;&lt;/span&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;" vertex="1">
          <mxGeometry height="168" width="270" x="540" y="257.5" as="geometry" />
        </mxCell>
        <mxCell id="nfsdQfqAbzpklse4fwm_-2" parent="nfsdQfqAbzpklse4fwm_-1" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="attributes" vertex="1">
          <mxGeometry height="20" width="270" y="55" as="geometry" />
        </mxCell>
        <mxCell id="nfsdQfqAbzpklse4fwm_-3" parent="nfsdQfqAbzpklse4fwm_-1" style="text;html=1;strokeColor=none;fillColor=none;align=left;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="- NotifyService notifyService&lt;div&gt;- FormularioCSERepository repository&lt;/div&gt;" vertex="1">
          <mxGeometry height="45" width="270" y="75" as="geometry" />
        </mxCell>
        <mxCell id="nfsdQfqAbzpklse4fwm_-5" parent="nfsdQfqAbzpklse4fwm_-1" style="line;strokeWidth=1;fillColor=none;align=left;verticalAlign=middle;spacingTop=-1;spacingLeft=3;spacingRight=3;rotatable=0;labelPosition=right;points=[];portConstraint=eastwest;" value="" vertex="1">
          <mxGeometry height="8" width="270" y="120" as="geometry" />
        </mxCell>
        <mxCell id="nfsdQfqAbzpklse4fwm_-6" parent="nfsdQfqAbzpklse4fwm_-1" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="operations" vertex="1">
          <mxGeometry height="20" width="270" y="128" as="geometry" />
        </mxCell>
        <mxCell id="nfsdQfqAbzpklse4fwm_-7" parent="nfsdQfqAbzpklse4fwm_-1" style="text;html=1;strokeColor=none;fillColor=none;align=left;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="update(FormularioCSE formulario)" vertex="1">
          <mxGeometry height="20" width="270" y="148" as="geometry" />
        </mxCell>
        <mxCell id="nfsdQfqAbzpklse4fwm_-11" edge="1" parent="1" source="fYSa4BK9EUfcGU9cp0zs-26" style="endArrow=none;startArrow=diamondThin;endFill=0;startFill=1;html=1;verticalAlign=bottom;labelBackgroundColor=none;strokeWidth=1;startSize=8;endSize=8;rounded=0;exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=0;entryY=0.25;entryDx=0;entryDy=0;" target="nfsdQfqAbzpklse4fwm_-1" value="">
          <mxGeometry relative="1" width="160" as="geometry">
            <mxPoint x="540" y="320" as="sourcePoint" />
            <mxPoint x="700" y="320" as="targetPoint" />
          </mxGeometry>
        </mxCell>
        <mxCell id="wHEjsySbuGyfIE5LMZYP-1" parent="1" style="swimlane;fontStyle=0;align=center;verticalAlign=top;childLayout=stackLayout;horizontal=1;startSize=55;horizontalStack=0;resizeParent=1;resizeParentMax=0;resizeLast=0;collapsible=0;marginBottom=0;html=1;whiteSpace=wrap;" value="&lt;br&gt;&lt;div&gt;&lt;b&gt;NotifyService&lt;/b&gt;&lt;/div&gt;" vertex="1">
          <mxGeometry height="168" width="270" x="890" y="100" as="geometry" />
        </mxCell>
        <mxCell id="wHEjsySbuGyfIE5LMZYP-2" parent="wHEjsySbuGyfIE5LMZYP-1" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="attributes" vertex="1">
          <mxGeometry height="20" width="270" y="55" as="geometry" />
        </mxCell>
        <mxCell id="wHEjsySbuGyfIE5LMZYP-3" parent="wHEjsySbuGyfIE5LMZYP-1" style="text;html=1;strokeColor=none;fillColor=none;align=left;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="- String url&lt;div&gt;- String usr&lt;/div&gt;&lt;div&gt;- String pas&lt;/div&gt;" vertex="1">
          <mxGeometry height="45" width="270" y="75" as="geometry" />
        </mxCell>
        <mxCell id="wHEjsySbuGyfIE5LMZYP-5" parent="wHEjsySbuGyfIE5LMZYP-1" style="line;strokeWidth=1;fillColor=none;align=left;verticalAlign=middle;spacingTop=-1;spacingLeft=3;spacingRight=3;rotatable=0;labelPosition=right;points=[];portConstraint=eastwest;" value="" vertex="1">
          <mxGeometry height="8" width="270" y="120" as="geometry" />
        </mxCell>
        <mxCell id="wHEjsySbuGyfIE5LMZYP-6" parent="wHEjsySbuGyfIE5LMZYP-1" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="operations" vertex="1">
          <mxGeometry height="20" width="270" y="128" as="geometry" />
        </mxCell>
        <mxCell id="wHEjsySbuGyfIE5LMZYP-7" parent="wHEjsySbuGyfIE5LMZYP-1" style="text;html=1;strokeColor=none;fillColor=none;align=left;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="send(String emisor, String remitente, String msg)" vertex="1">
          <mxGeometry height="20" width="270" y="148" as="geometry" />
        </mxCell>
        <mxCell id="wHEjsySbuGyfIE5LMZYP-8" edge="1" parent="1" source="nfsdQfqAbzpklse4fwm_-1" style="endArrow=none;startArrow=diamondThin;endFill=0;startFill=1;html=1;verticalAlign=bottom;labelBackgroundColor=none;strokeWidth=1;startSize=8;endSize=8;rounded=0;exitX=1.006;exitY=0.143;exitDx=0;exitDy=0;entryX=0;entryY=0.5;entryDx=0;entryDy=0;exitPerimeter=0;" target="wHEjsySbuGyfIE5LMZYP-3" value="">
          <mxGeometry relative="1" width="160" as="geometry">
            <mxPoint x="901" y="290" as="sourcePoint" />
            <mxPoint x="900" y="376" as="targetPoint" />
          </mxGeometry>
        </mxCell>
        <mxCell id="wHEjsySbuGyfIE5LMZYP-9" parent="1" style="swimlane;fontStyle=0;align=center;verticalAlign=top;childLayout=stackLayout;horizontal=1;startSize=55;horizontalStack=0;resizeParent=1;resizeParentMax=0;resizeLast=0;collapsible=0;marginBottom=0;html=1;whiteSpace=wrap;" value="&lt;b&gt;&lt;br&gt;&lt;/b&gt;&lt;div&gt;&lt;span style=&quot;text-align: left;&quot;&gt;&lt;b&gt;FormularioCSERepository&lt;/b&gt;&lt;/span&gt;&lt;/div&gt;" vertex="1">
          <mxGeometry height="210" width="330" x="890" y="385" as="geometry" />
        </mxCell>
        <mxCell id="wHEjsySbuGyfIE5LMZYP-10" parent="wHEjsySbuGyfIE5LMZYP-9" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="attributes" vertex="1">
          <mxGeometry height="20" width="330" y="55" as="geometry" />
        </mxCell>
        <mxCell id="wHEjsySbuGyfIE5LMZYP-11" parent="wHEjsySbuGyfIE5LMZYP-9" style="text;html=1;strokeColor=none;fillColor=none;align=left;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="- OracleConexion oracleConexion" vertex="1">
          <mxGeometry height="45" width="330" y="75" as="geometry" />
        </mxCell>
        <mxCell id="wHEjsySbuGyfIE5LMZYP-12" parent="wHEjsySbuGyfIE5LMZYP-9" style="line;strokeWidth=1;fillColor=none;align=left;verticalAlign=middle;spacingTop=-1;spacingLeft=3;spacingRight=3;rotatable=0;labelPosition=right;points=[];portConstraint=eastwest;" value="" vertex="1">
          <mxGeometry height="8" width="330" y="120" as="geometry" />
        </mxCell>
        <mxCell id="wHEjsySbuGyfIE5LMZYP-13" parent="wHEjsySbuGyfIE5LMZYP-9" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="operations" vertex="1">
          <mxGeometry height="20" width="330" y="128" as="geometry" />
        </mxCell>
        <mxCell id="wHEjsySbuGyfIE5LMZYP-14" parent="wHEjsySbuGyfIE5LMZYP-9" style="text;html=1;strokeColor=none;fillColor=none;align=left;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="+ actualizarFormularioCSE(FormularioCSE formulario)" vertex="1">
          <mxGeometry height="62" width="330" y="148" as="geometry" />
        </mxCell>
        <mxCell id="wHEjsySbuGyfIE5LMZYP-15" edge="1" parent="1" source="nfsdQfqAbzpklse4fwm_-3" style="endArrow=none;startArrow=diamondThin;endFill=0;startFill=1;html=1;verticalAlign=bottom;labelBackgroundColor=none;strokeWidth=1;startSize=8;endSize=8;rounded=0;exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=-0.004;entryY=0.111;entryDx=0;entryDy=0;entryPerimeter=0;" target="wHEjsySbuGyfIE5LMZYP-9" value="">
          <mxGeometry relative="1" width="160" as="geometry">
            <mxPoint x="840" y="334" as="sourcePoint" />
            <mxPoint x="918" y="250" as="targetPoint" />
          </mxGeometry>
        </mxCell>
        <mxCell id="5SZzQecO503x7io3iQBx-1" parent="1" style="swimlane;fontStyle=0;align=center;verticalAlign=top;childLayout=stackLayout;horizontal=1;startSize=55;horizontalStack=0;resizeParent=1;resizeParentMax=0;resizeLast=0;collapsible=0;marginBottom=0;html=1;whiteSpace=wrap;" value="&lt;div&gt;&lt;b&gt;&lt;br&gt;&lt;/b&gt;&lt;/div&gt;&lt;b&gt;OracleConexion&lt;/b&gt;" vertex="1">
          <mxGeometry height="168" width="270" x="1300" y="595" as="geometry" />
        </mxCell>
        <mxCell id="5SZzQecO503x7io3iQBx-2" parent="5SZzQecO503x7io3iQBx-1" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="attributes" vertex="1">
          <mxGeometry height="20" width="270" y="55" as="geometry" />
        </mxCell>
        <mxCell id="5SZzQecO503x7io3iQBx-3" parent="5SZzQecO503x7io3iQBx-1" style="text;html=1;strokeColor=none;fillColor=none;align=left;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="- String jdbcURL&lt;div&gt;- String usr&lt;/div&gt;&lt;div&gt;- String pas&lt;/div&gt;" vertex="1">
          <mxGeometry height="45" width="270" y="75" as="geometry" />
        </mxCell>
        <mxCell id="5SZzQecO503x7io3iQBx-4" parent="5SZzQecO503x7io3iQBx-1" style="line;strokeWidth=1;fillColor=none;align=left;verticalAlign=middle;spacingTop=-1;spacingLeft=3;spacingRight=3;rotatable=0;labelPosition=right;points=[];portConstraint=eastwest;" value="" vertex="1">
          <mxGeometry height="8" width="270" y="120" as="geometry" />
        </mxCell>
        <mxCell id="5SZzQecO503x7io3iQBx-5" parent="5SZzQecO503x7io3iQBx-1" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="operations" vertex="1">
          <mxGeometry height="20" width="270" y="128" as="geometry" />
        </mxCell>
        <mxCell id="5SZzQecO503x7io3iQBx-6" parent="5SZzQecO503x7io3iQBx-1" style="text;html=1;strokeColor=none;fillColor=none;align=left;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="+ getConexion()" vertex="1">
          <mxGeometry height="20" width="270" y="148" as="geometry" />
        </mxCell>
        <mxCell id="5SZzQecO503x7io3iQBx-7" edge="1" parent="1" style="endArrow=none;startArrow=diamondThin;endFill=0;startFill=1;html=1;verticalAlign=bottom;labelBackgroundColor=none;strokeWidth=1;startSize=8;endSize=8;rounded=0;exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=0;entryY=0.25;entryDx=0;entryDy=0;" target="5SZzQecO503x7io3iQBx-1" value="">
          <mxGeometry relative="1" width="160" as="geometry">
            <mxPoint x="1220" y="490" as="sourcePoint" />
            <mxPoint x="1300" y="573" as="targetPoint" />
          </mxGeometry>
        </mxCell>
        <mxCell id="5SZzQecO503x7io3iQBx-8" parent="1" style="swimlane;fontStyle=0;align=center;verticalAlign=top;childLayout=stackLayout;horizontal=1;startSize=55;horizontalStack=0;resizeParent=1;resizeParentMax=0;resizeLast=0;collapsible=0;marginBottom=0;html=1;whiteSpace=wrap;" value="&lt;br&gt;&lt;b&gt;GetFormularioCSERestController&lt;/b&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;" vertex="1">
          <mxGeometry height="163" width="270" x="190" y="530" as="geometry" />
        </mxCell>
        <mxCell id="5SZzQecO503x7io3iQBx-9" parent="5SZzQecO503x7io3iQBx-8" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="attributes" vertex="1">
          <mxGeometry height="20" width="270" y="55" as="geometry" />
        </mxCell>
        <mxCell id="5SZzQecO503x7io3iQBx-10" parent="5SZzQecO503x7io3iQBx-8" style="text;html=1;strokeColor=none;fillColor=none;align=left;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="ObtenerFormularioCSEService&amp;nbsp;service" vertex="1">
          <mxGeometry height="20" width="270" y="75" as="geometry" />
        </mxCell>
        <mxCell id="5SZzQecO503x7io3iQBx-11" parent="5SZzQecO503x7io3iQBx-8" style="text;html=1;strokeColor=none;fillColor=none;align=left;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="..." vertex="1">
          <mxGeometry height="20" width="270" y="95" as="geometry" />
        </mxCell>
        <mxCell id="5SZzQecO503x7io3iQBx-12" parent="5SZzQecO503x7io3iQBx-8" style="line;strokeWidth=1;fillColor=none;align=left;verticalAlign=middle;spacingTop=-1;spacingLeft=3;spacingRight=3;rotatable=0;labelPosition=right;points=[];portConstraint=eastwest;" value="" vertex="1">
          <mxGeometry height="8" width="270" y="115" as="geometry" />
        </mxCell>
        <mxCell id="5SZzQecO503x7io3iQBx-13" parent="5SZzQecO503x7io3iQBx-8" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="operations" vertex="1">
          <mxGeometry height="20" width="270" y="123" as="geometry" />
        </mxCell>
        <mxCell id="5SZzQecO503x7io3iQBx-14" parent="5SZzQecO503x7io3iQBx-8" style="text;html=1;strokeColor=none;fillColor=none;align=left;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="update(FormularioCSE formulario)" vertex="1">
          <mxGeometry height="20" width="270" y="143" as="geometry" />
        </mxCell>
        <mxCell id="_FJOJ2Gb8WDwC82pApPQ-1" parent="1" style="swimlane;fontStyle=0;align=center;verticalAlign=top;childLayout=stackLayout;horizontal=1;startSize=55;horizontalStack=0;resizeParent=1;resizeParentMax=0;resizeLast=0;collapsible=0;marginBottom=0;html=1;whiteSpace=wrap;" value="&lt;br&gt;&lt;div style=&quot;text-align: left;&quot;&gt;&lt;span style=&quot;background-color: transparent;&quot;&gt;&lt;b&gt;ObtenerFormularioCSEService&lt;/b&gt;&lt;/span&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;" vertex="1">
          <mxGeometry height="168" width="320" x="510" y="530" as="geometry" />
        </mxCell>
        <mxCell id="_FJOJ2Gb8WDwC82pApPQ-2" parent="_FJOJ2Gb8WDwC82pApPQ-1" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="attributes" vertex="1">
          <mxGeometry height="20" width="320" y="55" as="geometry" />
        </mxCell>
        <mxCell id="_FJOJ2Gb8WDwC82pApPQ-3" parent="_FJOJ2Gb8WDwC82pApPQ-1" style="text;html=1;strokeColor=none;fillColor=none;align=left;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="&lt;div&gt;- FormularioCSERepository formularioCSErepository&lt;/div&gt;&lt;div&gt;- UserSystemRepository userRepository&lt;/div&gt;" vertex="1">
          <mxGeometry height="45" width="320" y="75" as="geometry" />
        </mxCell>
        <mxCell id="_FJOJ2Gb8WDwC82pApPQ-4" parent="_FJOJ2Gb8WDwC82pApPQ-1" style="line;strokeWidth=1;fillColor=none;align=left;verticalAlign=middle;spacingTop=-1;spacingLeft=3;spacingRight=3;rotatable=0;labelPosition=right;points=[];portConstraint=eastwest;" value="" vertex="1">
          <mxGeometry height="8" width="320" y="120" as="geometry" />
        </mxCell>
        <mxCell id="_FJOJ2Gb8WDwC82pApPQ-5" parent="_FJOJ2Gb8WDwC82pApPQ-1" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="operations" vertex="1">
          <mxGeometry height="20" width="320" y="128" as="geometry" />
        </mxCell>
        <mxCell id="_FJOJ2Gb8WDwC82pApPQ-6" parent="_FJOJ2Gb8WDwC82pApPQ-1" style="text;html=1;strokeColor=none;fillColor=none;align=left;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="get(String usrSystem)" vertex="1">
          <mxGeometry height="20" width="320" y="148" as="geometry" />
        </mxCell>
        <mxCell id="_FJOJ2Gb8WDwC82pApPQ-7" parent="1" style="swimlane;fontStyle=0;align=center;verticalAlign=top;childLayout=stackLayout;horizontal=1;startSize=55;horizontalStack=0;resizeParent=1;resizeParentMax=0;resizeLast=0;collapsible=0;marginBottom=0;html=1;whiteSpace=wrap;" value="&lt;b&gt;&lt;br&gt;&lt;/b&gt;&lt;div&gt;&lt;span style=&quot;text-align: left;&quot;&gt;&lt;b&gt;UserSystemRepository&lt;/b&gt;&lt;/span&gt;&lt;/div&gt;" vertex="1">
          <mxGeometry height="210" width="330" x="890" y="670" as="geometry" />
        </mxCell>
        <mxCell id="_FJOJ2Gb8WDwC82pApPQ-8" parent="_FJOJ2Gb8WDwC82pApPQ-7" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="attributes" vertex="1">
          <mxGeometry height="20" width="330" y="55" as="geometry" />
        </mxCell>
        <mxCell id="_FJOJ2Gb8WDwC82pApPQ-9" parent="_FJOJ2Gb8WDwC82pApPQ-7" style="text;html=1;strokeColor=none;fillColor=none;align=left;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="- OracleConexion oracleConexion" vertex="1">
          <mxGeometry height="45" width="330" y="75" as="geometry" />
        </mxCell>
        <mxCell id="_FJOJ2Gb8WDwC82pApPQ-10" parent="_FJOJ2Gb8WDwC82pApPQ-7" style="line;strokeWidth=1;fillColor=none;align=left;verticalAlign=middle;spacingTop=-1;spacingLeft=3;spacingRight=3;rotatable=0;labelPosition=right;points=[];portConstraint=eastwest;" value="" vertex="1">
          <mxGeometry height="8" width="330" y="120" as="geometry" />
        </mxCell>
        <mxCell id="_FJOJ2Gb8WDwC82pApPQ-11" parent="_FJOJ2Gb8WDwC82pApPQ-7" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="operations" vertex="1">
          <mxGeometry height="20" width="330" y="128" as="geometry" />
        </mxCell>
        <mxCell id="_FJOJ2Gb8WDwC82pApPQ-12" parent="_FJOJ2Gb8WDwC82pApPQ-7" style="text;html=1;strokeColor=none;fillColor=none;align=left;verticalAlign=middle;spacingLeft=4;spacingRight=4;overflow=hidden;rotatable=0;points=[[0,0.5],[1,0.5]];portConstraint=eastwest;whiteSpace=wrap;" value="+ find(String userSystem)" vertex="1">
          <mxGeometry height="62" width="330" y="148" as="geometry" />
        </mxCell>
        <mxCell id="_FJOJ2Gb8WDwC82pApPQ-13" edge="1" parent="1" source="_FJOJ2Gb8WDwC82pApPQ-9" style="endArrow=none;startArrow=diamondThin;endFill=0;startFill=1;html=1;verticalAlign=bottom;labelBackgroundColor=none;strokeWidth=1;startSize=8;endSize=8;rounded=0;exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=0;entryY=0.25;entryDx=0;entryDy=0;" target="5SZzQecO503x7io3iQBx-1" value="">
          <mxGeometry relative="1" width="160" as="geometry">
            <mxPoint x="1260" y="518" as="sourcePoint" />
            <mxPoint x="1350" y="450" as="targetPoint" />
          </mxGeometry>
        </mxCell>
        <mxCell id="_FJOJ2Gb8WDwC82pApPQ-14" edge="1" parent="1" source="_FJOJ2Gb8WDwC82pApPQ-3" style="endArrow=none;startArrow=diamondThin;endFill=0;startFill=1;html=1;verticalAlign=bottom;labelBackgroundColor=none;strokeWidth=1;startSize=8;endSize=8;rounded=0;exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=0.006;entryY=0.127;entryDx=0;entryDy=0;entryPerimeter=0;" target="_FJOJ2Gb8WDwC82pApPQ-7" value="">
          <mxGeometry relative="1" width="160" as="geometry">
            <mxPoint x="850" y="410" as="sourcePoint" />
            <mxPoint x="930" y="493" as="targetPoint" />
          </mxGeometry>
        </mxCell>
        <mxCell id="_FJOJ2Gb8WDwC82pApPQ-15" edge="1" parent="1" source="_FJOJ2Gb8WDwC82pApPQ-3" style="endArrow=none;startArrow=diamondThin;endFill=0;startFill=1;html=1;verticalAlign=bottom;labelBackgroundColor=none;strokeWidth=1;startSize=8;endSize=8;rounded=0;exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=-0.004;entryY=0.135;entryDx=0;entryDy=0;entryPerimeter=0;" target="wHEjsySbuGyfIE5LMZYP-9" value="">
          <mxGeometry relative="1" width="160" as="geometry">
            <mxPoint x="850" y="680" as="sourcePoint" />
            <mxPoint x="932" y="719" as="targetPoint" />
          </mxGeometry>
        </mxCell>
        <mxCell id="_FJOJ2Gb8WDwC82pApPQ-16" edge="1" parent="1" source="5SZzQecO503x7io3iQBx-10" style="endArrow=none;startArrow=diamondThin;endFill=0;startFill=1;html=1;verticalAlign=bottom;labelBackgroundColor=none;strokeWidth=1;startSize=8;endSize=8;rounded=0;exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=0;entryY=0.25;entryDx=0;entryDy=0;" target="_FJOJ2Gb8WDwC82pApPQ-1" value="">
          <mxGeometry relative="1" width="160" as="geometry">
            <mxPoint x="860" y="360" as="sourcePoint" />
            <mxPoint x="939" y="413" as="targetPoint" />
          </mxGeometry>
        </mxCell>
        <mxCell id="IRddg57-LPZgbZA5LEF2-4" edge="1" parent="1" source="IRddg57-LPZgbZA5LEF2-3" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;entryX=0;entryY=0.5;entryDx=0;entryDy=0;" target="fYSa4BK9EUfcGU9cp0zs-26">
          <mxGeometry relative="1" as="geometry" />
        </mxCell>
        <mxCell id="IRddg57-LPZgbZA5LEF2-3" parent="1" style="ellipse;" value="" vertex="1">
          <mxGeometry height="30" width="30" x="80" y="340" as="geometry" />
        </mxCell>
        <mxCell id="IRddg57-LPZgbZA5LEF2-5" edge="1" parent="1" source="IRddg57-LPZgbZA5LEF2-6" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;entryX=0;entryY=0.5;entryDx=0;entryDy=0;">
          <mxGeometry relative="1" as="geometry">
            <mxPoint x="190" y="614" as="targetPoint" />
          </mxGeometry>
        </mxCell>
        <mxCell id="IRddg57-LPZgbZA5LEF2-6" parent="1" style="ellipse;" value="" vertex="1">
          <mxGeometry height="30" width="30" x="80" y="599" as="geometry" />
        </mxCell>
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>
